Server:
  port: 8088

spring:
  application:
    name: email-service
  cloud:
    config:
      enabled: false
  eureka:
    client:
      enabled: true
      service-url:
        defaultZone:  http://localhost:8761/eureka/